language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - pip install -e . --use-mirrors
before_script:
  - pip install -r requirements.txt --use-mirrors
# command to run tests
script: nosetests -v tests
after_success:
  - coveralls