language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
before_script:
  - pip install -r requirements.txt --use-mirrors
# command to run tests
script: nosetests -v --with-coverage tests
after_success:
  - coveralls