language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - "pip install python-coveralls"
script: nosetests --with-coverage --cover-package=pycnpfj.cpf --cover-package=pycnpfj.cnpj --cover-package=pycnpfj.calculation --cover-package=pycnpfj.cnpfj
after_success:
  - coveralls --base_dir pycnpfj/
