language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - "pip install python-coveralls"
script: nosetests --with-coverage --cover-package=pycpfcnpj.cpf --cover-package=pycpfcnpj.cnpj --cover-package=pycpfcnpj.calculation --cover-package=pycpfcnpj.cpfcnpj
after_success:
  - coveralls --base_dir pycpfcnpj/
